### ISSUE TITLE
Birdform Breaks CAB

### ISSUE THREAD

**Issue by frazazel** [Sibusten/multicab-extended#1]
I stumbled on this great extension, and I really like it. I was playing around with birdform, though, and the CAB just shows up entirely empty, and I furthermore can't even click any skills from the dropdown menu. I need to click the "show old combat menu" link at the bottom and then select an action, each and every round of combat.

Since you can't use most skills or items while in birdform anyway, you might want to do a quick check to see if you have the birdform effect active, and prevent making any changes to the fight page if so, reverting to regular CAB for these fights.

**Comment by Sibusten** [comment]
Thanks for the report. Just checked and it's very buggy yeah. Added a quick disable when birdform is active (5bbf742)

`svn update` to get the fix ^^
